{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"name":"07_Python_Error_Handling.ipynb","provenance":[],"collapsed_sections":[],"toc_visible":true,"authorship_tag":"ABX9TyNL4lH5Xp7yPO+/Gg7t6Q1w"},"kernelspec":{"name":"python3","display_name":"Python 3"}},"cells":[{"cell_type":"markdown","metadata":{"id":"ewQmTZFkdFrP","colab_type":"text"},"source":["# Python Overview\n","\n","This tutorial was written by Terry L. Ruas (University of Wuppertal). The references for external contributors for which this material was anyhow adapted/inspired are in the **Acknowledgments** section (end of the document)."]},{"cell_type":"markdown","metadata":{"id":"tQXj0RInUmgk","colab_type":"text"},"source":["#Python Error Handling\n","\n","This notebook will cover the following topics:\n","\n","1. Error Handling\n","\n"]},{"cell_type":"markdown","metadata":{"id":"YOAoMZ3LY88W","colab_type":"text"},"source":["# Error Handling\n","\n","We want to avoid a program crash/shutdown due to unexpected behavior\n","\n","Our programs need to be robust to deal with:\n","* User input\n","* Logical error\n","* Unexpected behavior\n","* â€¦\n"]},{"cell_type":"markdown","metadata":{"id":"VOX4k4hWY9Iw","colab_type":"text"},"source":["For example, the code below is not very error-proof. Try to input anything different than an `int`. The functions will fail miserably.\n","\n"]},{"cell_type":"code","metadata":{"id":"72swwToVZg6s","colab_type":"code","colab":{}},"source":["# Non error proof code\n","def read_int1():\n","    \"\"\"Read an integer from the user.\"\"\"\n","    return int(input(\"Please enter a number:\\n\"))\n","\n","print(\"Result: \",read_int1())"],"execution_count":0,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"qyEE-3iEaOvR","colab_type":"text"},"source":["Let us try to improve our code by trying to execute something. In case it does not run we will display an error."]},{"cell_type":"code","metadata":{"id":"0IPQlrYrY9M9","colab_type":"code","colab":{"base_uri":"https://localhost:8080/","height":69},"outputId":"e750e03b-4947-480e-9b08-420be9f0a064","executionInfo":{"status":"ok","timestamp":1588071807077,"user_tz":-120,"elapsed":3078,"user":{"displayName":"Terry Lima Ruas","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GhJERmQ3aZ6mGu8-GzgAINsrNPvbcsDYi6Eo4xo=s64","userId":"06773980904201109859"}}},"source":["# try to provide a string to see the result\n","def read_int2():\n","    \"\"\"Read an integer from the user (better).\"\"\"\n","    try:\n","        x = int(input(\"Please enter a number:\\n\"))\n","        print(x)\n","    except ValueError:\n","        print(\"Oops! Invalid input. Try again...\")\n","    \n","\n","read_int2()"],"execution_count":20,"outputs":[{"output_type":"stream","text":["Please enter a number:\n","erer\n","Oops! Invalid input. Try again...\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"bAF8QOczavlH","colab_type":"text"},"source":["We can try to capture specific errors given certain situations. In case the `try` part fails, it will trigger the except part.\n","\n","For example:"]},{"cell_type":"code","metadata":{"id":"e3Mltxdpal17","colab_type":"code","colab":{"base_uri":"https://localhost:8080/","height":360},"outputId":"6a949727-dc32-46bb-8f43-cefd3a6ebdb0","executionInfo":{"status":"error","timestamp":1588071830340,"user_tz":-120,"elapsed":2478,"user":{"displayName":"Terry Lima Ruas","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GhJERmQ3aZ6mGu8-GzgAINsrNPvbcsDYi6Eo4xo=s64","userId":"06773980904201109859"}}},"source":["def read_int3():\n","    \"\"\"Read an integer from the user (better).\"\"\"\n","    try:\n","        x = int(input(\"Please enter a number:\\n\"))\n","        print(x)\n","    except ConnectionError: # here we have a connection error\n","        print(\"Oops! A connection Error...\")\n","\n","read_int3()\n"],"execution_count":21,"outputs":[{"output_type":"stream","text":["Please enter a number:\n","as\n"],"name":"stdout"},{"output_type":"error","ename":"ValueError","evalue":"ignored","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mValueError\u001b[0m                                Traceback (most recent call last)","\u001b[0;32m<ipython-input-21-2cb57a0ebac4>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      7\u001b[0m         \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"Oops! A connection Error...\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      8\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 9\u001b[0;31m \u001b[0mread_int3\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;32m<ipython-input-21-2cb57a0ebac4>\u001b[0m in \u001b[0;36mread_int3\u001b[0;34m()\u001b[0m\n\u001b[1;32m      2\u001b[0m     \u001b[0;34m\"\"\"Read an integer from the user (better).\"\"\"\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      3\u001b[0m     \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 4\u001b[0;31m         \u001b[0mx\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0minput\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"Please enter a number:\\n\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      5\u001b[0m         \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mx\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      6\u001b[0m     \u001b[0;32mexcept\u001b[0m \u001b[0mConnectionError\u001b[0m\u001b[0;34m:\u001b[0m \u001b[0;31m# here we have a connection error\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;31mValueError\u001b[0m: invalid literal for int() with base 10: 'as'"]}]},{"cell_type":"markdown","metadata":{"id":"LYzp1Q1qbZTi","colab_type":"text"},"source":["Notice the code above was designed to capture a `Connection Error`. However, we are getting a `Value Error` if we provide an a value different the one expected. As a result, the error category were are monitoring was not triggered and a generic-standard message was presented.\n","\n","The best scenario is to capture the correct error, given the situation, which is not always the easiest thing. For that reason, some approaches use generic `error` types to capture undesired outcomes. For example:"]},{"cell_type":"code","metadata":{"id":"UzTQBVqebFOD","colab_type":"code","colab":{"base_uri":"https://localhost:8080/","height":69},"outputId":"984b0a30-8831-404b-e819-feb276d703cb","executionInfo":{"status":"ok","timestamp":1588071852684,"user_tz":-120,"elapsed":4261,"user":{"displayName":"Terry Lima Ruas","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GhJERmQ3aZ6mGu8-GzgAINsrNPvbcsDYi6Eo4xo=s64","userId":"06773980904201109859"}}},"source":["def read_int4():\n","    \"\"\"Read an integer from the user (better).\"\"\"\n","    try:\n","        x = int(input(\"Please enter a number:\\n\"))\n","        print(x)\n","    except:  # we are not specifying which error, if something goes bad we are interested!\n","        print('Oops! Something went wrong..')\n","\n","read_int4()"],"execution_count":22,"outputs":[{"output_type":"stream","text":["Please enter a number:\n","qqq\n","Oops! Something went wrong..\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"qlxp5HPwcLTK","colab_type":"text"},"source":["We don't necessarily need to capture one error at a time, we can also group them. For example:"]},{"cell_type":"code","metadata":{"id":"gwNe-frRY9Qj","colab_type":"code","colab":{"base_uri":"https://localhost:8080/","height":69},"outputId":"7dfcc2d5-eac6-461d-c7ec-02d0951aa714","executionInfo":{"status":"ok","timestamp":1588072218778,"user_tz":-120,"elapsed":3644,"user":{"displayName":"Terry Lima Ruas","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GhJERmQ3aZ6mGu8-GzgAINsrNPvbcsDYi6Eo4xo=s64","userId":"06773980904201109859"}}},"source":["def this_fails():\n","  # When using this function, we encapsulate it in a try-catch block\n","  # and if any of the suggested error appear, we will display the same message\n","    try:\n","        number = input(\"Provide a number for division\\n\")\n","        result = 1/float(number)\n","        print('Division results: ', result)\n","    except (ZeroDivisionError, ValueError) as err:\n","        print('Handling run-time error:', err) \n","\n","# In addition to the exception we are alsoprinting the std-err for the given category.\n","# provide 0 as input, and later a string such as \"python\"\n","\n","this_fails()\n"],"execution_count":28,"outputs":[{"output_type":"stream","text":["Provide a number for division\n","python\n","Handling run-time error: could not convert string to float: 'python'\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"GlZNOiqjfHsF","colab_type":"text"},"source":["We can have one special message for each type of error as well. We just need to concatenate the error elements."]},{"cell_type":"code","metadata":{"id":"t2Upj_aVY9T2","colab_type":"code","colab":{"base_uri":"https://localhost:8080/","height":69},"outputId":"a9ec5aaa-0deb-4a0d-8534-282718736483","executionInfo":{"status":"ok","timestamp":1588072420507,"user_tz":-120,"elapsed":2655,"user":{"displayName":"Terry Lima Ruas","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GhJERmQ3aZ6mGu8-GzgAINsrNPvbcsDYi6Eo4xo=s64","userId":"06773980904201109859"}}},"source":["def that_fails():\n","  # When using this function, we encapsulate it in a try-catch block\n","  # and if any of the suggested error appear, we will display different messages\n","    try:\n","        number = input(\"Provide a number for division\\n\")\n","        result = 1/float(number)\n","        print('Division results: ', result)\n","    except ZeroDivisionError as err:\n","        print('Handling run-time error:', err)\n","    except ValueError as err:\n","        print('Invalid input: ', err)\n","\n","# provide 0 as input, and later a string such as \"python\" to see the different messages\n","that_fails()\n","\n","\n","\n"],"execution_count":32,"outputs":[{"output_type":"stream","text":["Provide a number for division\n","python\n","Invalid input:  could not convert string to float: 'python'\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"QziUc60IfpXj","colab_type":"text"},"source":["As we said, for each situation we can expect a type of error. Since this can be quite challenging we can try to predict some errors, and leave a generic one just in case.\n","\n","In the code below we will try to open a file, and will try to catch an `OSError` and a `ValueError`. If we are not able to capture any of the aforementioned errors, we will simply rely on the generic exception."]},{"cell_type":"code","metadata":{"id":"6F-MKSiEY9XK","colab_type":"code","colab":{"base_uri":"https://localhost:8080/","height":34},"outputId":"5eb570b2-df99-49b6-e915-b0a3adaf3a38","executionInfo":{"status":"ok","timestamp":1588072973406,"user_tz":-120,"elapsed":574,"user":{"displayName":"Terry Lima Ruas","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GhJERmQ3aZ6mGu8-GzgAINsrNPvbcsDYi6Eo4xo=s64","userId":"06773980904201109859"}}},"source":["import sys\n","\n","try:\n","    f = open('data/myfileZ.txt') #data/myfile.txt\n","    s = f.readline()\n","    i = int(s.strip())\n","except OSError as err: # a wrong file name will trigger this OS error\n","    print(\"OS error: {0}\".format(err))\n","except ValueError:  # If the value is not the one excpected this error is trigger\n","    print(\"Could not convert data to an integer.\")\n","except:  # if the error does not fit in one of the predicted errors, this one is triggered\n","    print(\"Unexpected error:\", sys.exc_info()[0])\n","    raise\n"],"execution_count":37,"outputs":[{"output_type":"stream","text":["OS error: [Errno 2] No such file or directory: 'data/myfileZ.txt'\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"4CUcTPUvhupk","colab_type":"text"},"source":["The `finally` clause makes sure that no matter the outcome the statements in this block will run."]},{"cell_type":"code","metadata":{"id":"1PnrtXUnY9aV","colab_type":"code","colab":{"base_uri":"https://localhost:8080/","height":52},"outputId":"471a8f4a-e937-4187-f5f3-6f9c2c1a844e","executionInfo":{"status":"ok","timestamp":1588073075973,"user_tz":-120,"elapsed":575,"user":{"displayName":"Terry Lima Ruas","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GhJERmQ3aZ6mGu8-GzgAINsrNPvbcsDYi6Eo4xo=s64","userId":"06773980904201109859"}}},"source":["import sys\n","\n","try:\n","    f = open('cake.txt') # this files not exist, so the OSError should be triggered\n","    s = f.readline()\n","    i = int(s.strip())\n","except OSError as err:\n","    print(\"OS error: {0}\".format(err))\n","finally:\n","    print('There is no scape, I will run no matter what!')"],"execution_count":38,"outputs":[{"output_type":"stream","text":["OS error: [Errno 2] No such file or directory: 'cake.txt'\n","There is no scape, I will run no matter what!\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"_Z6s_ktXiILy","colab_type":"text"},"source":["## Http Error\n","\n","This is an example of HTTP error capture.\n","\n","Try to provide an invalid url to see what happens."]},{"cell_type":"code","metadata":{"id":"m8-Q6OJhiIit","colab_type":"code","colab":{"base_uri":"https://localhost:8080/","height":104},"outputId":"42281284-160d-48c8-c287-2c53a2c4d405","executionInfo":{"status":"ok","timestamp":1588073455744,"user_tz":-120,"elapsed":590,"user":{"displayName":"Terry Lima Ruas","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GhJERmQ3aZ6mGu8-GzgAINsrNPvbcsDYi6Eo4xo=s64","userId":"06773980904201109859"}}},"source":["from urllib.request import urlopen\n","from urllib.error import HTTPError\n","from urllib.error import URLError\n","\n","\n","def open_url(url):\n","    try:\n","        html = urlopen(url)\n","        doc = html.read().decode(\"utf-8\")\n","        html.close()\n","        return doc\n","    except HTTPError as http_e:\n","        print(\"%s while connecting to: %s\" %(http_e, url))\n","        return None\n","    except URLError as url_e:\n","        print(\"%s while connecting to: %s\" %(url_e, url))\n","        return None\n","\n","\n","print(\"\\nHTTP Connection:\")\n","print(\"===========================\")\n","url = \"https://dke.uni-wuppertal.de/en/\" # provide an invalid url such as \"https://dke.uniwuppertal.de/en/\"\n","print(\"Trying to connect to: \" + url)\n","html = open_url(url)\n","if html != None:\n","    print(html[0:200])"],"execution_count":41,"outputs":[{"output_type":"stream","text":["\n","HTTP Connection:\n","===========================\n","Trying to connect to: https://dke.unwuppertal.de/en/\n","<urlopen error [Errno -2] Name or service not known> while connecting to: https://dke.unwuppertal.de/en/\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"ewgpynF0iIpp","colab_type":"text"},"source":["## General Error Workflow\n","\n","1. The try clause (the statement(s) between the try and except keywords) is executed\n","\n","2. If no exception occurs, the except clause is skipped and execution of the try statement is finished\n","\n","3. If an exception occurs during execution of the try clause, the rest of the clause is skipped\n","  * Then if its type matches the exception named after the except keyword, the except clause is executed, and then execution continues after the try statement\n","  * If an exception occurs which does not match the exception named in the except clause, it is passed on to outer try statements;\n","  * If no handler is found, it is an unhandled exception and execution stops with a message as shown above."]},{"cell_type":"markdown","metadata":{"id":"ygb0aFTDNsKX","colab_type":"text"},"source":["#Acknowledgements\n","\n","* Redmond, Hsu, Saini, Gupta, Ramsey, Kondrich, Capoor, Cohen, Borus, Kincaid, Malik, and many others. - Stanford CS41 "]},{"cell_type":"code","metadata":{"id":"Rje4v06SbT3q","colab_type":"code","colab":{}},"source":[""],"execution_count":0,"outputs":[]}]}